-- =============================================================================
--  V1 — Initial schema: app_role, batch_source_system, batch_job_history
--
--  batch_processing_statistics has been removed — batch_job_history is the
--  single backing table for the BPS module.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. app_role seed (BPS-003, BPS-009)
-- ---------------------------------------------------------------------------
INSERT INTO app_role (id, role_name, description)
VALUES
    (1, 'Admin',        'UI read access and API GET. Cannot POST or PUT.'),
    (2, 'Manager',      'UI read access and API GET. Cannot POST or PUT.'),
    (3, 'Sr. Analyst',  'UI read access and API GET. Cannot POST or PUT.'),
    (4, 'Analyst',      'UI read access and API GET. Cannot POST or PUT.'),
    (5, 'Batch Runner', 'Service principal. API POST and PUT only. No UI. Credentials via CyberArk.')
ON CONFLICT (role_name) DO UPDATE
    SET description = EXCLUDED.description;

-- ---------------------------------------------------------------------------
-- 2. batch_source_system
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS batch_source_system (
    id           bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
                     ( INCREMENT 1 START 1 MINVALUE 1
                       MAXVALUE 9223372036854775807 CACHE 1 ),
    source_name  character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description  character varying(500) COLLATE pg_catalog."default",
    channel_type character varying(100) COLLATE pg_catalog."default",
    status       character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT batch_source_system_pkey PRIMARY KEY (id)
);

INSERT INTO batch_source_system (source_name, description, channel_type, status)
VALUES
    ('SIMS', NULL, NULL, NULL),
    ('RRPS', NULL, NULL, NULL),
    ('CBIS', NULL, NULL, NULL)
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. batch_job_history  — primary BPS backing table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS batch_job_history (
    id                               bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY
                                                 ( INCREMENT 1 START 1 MINVALUE 1
                                                   MAXVALUE 9223372036854775807 CACHE 1 ),
    job_id                           bigint,
    job_type                         character varying(100) COLLATE pg_catalog."default"
                                         NOT NULL DEFAULT '',
    retry_count                      integer,
    job_status                       character varying(50)  COLLATE pg_catalog."default"
                                         NOT NULL DEFAULT '',
    start_time                       timestamp with time zone,
    end_time                         timestamp with time zone,
    status                           character varying(100) COLLATE pg_catalog."default"
                                         NOT NULL DEFAULT '',
    error_message                    character varying(500) COLLATE pg_catalog."default",
    source_system_id                 bigint NOT NULL,
    records_changed                  integer,
    records_gathered                 integer,
    records_processed_current_period integer,
    records_processed_prior_period   integer,
    records_unpostable               integer,
    CONSTRAINT batch_job_history_pkey PRIMARY KEY (id),
    CONSTRAINT fk_batch_job_history_source_system
        FOREIGN KEY (source_system_id)
        REFERENCES batch_source_system (id)
);

CREATE INDEX IF NOT EXISTS idx_batch_job_history_source_system_start_time
    ON batch_job_history (source_system_id, start_time DESC);

CREATE INDEX IF NOT EXISTS idx_batch_job_history_job_status
    ON batch_job_history (job_status);

CREATE INDEX IF NOT EXISTS idx_batch_job_history_job_type_lower
    ON batch_job_history (LOWER(job_type));
